h5_files_per_split: null
data_dir: /home/deepaknayak/Documents/Reinforcement-learning/imitation-learning/data/imitation_learning/h5_files/h5_files/AgentHuman/
preproc_output_dir: /home/deepaknayak/Documents/Reinforcement-learning/imitation-learning/data/imitation_learning/preprocessed
